"""deleted column

Revision ID: 8c6b7cee48cd
Revises: cd4c6a16e9d8
Create Date: 2019-07-22 20:35:25.444535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6b7cee48cd'
down_revision = 'cd4c6a16e9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('predictions', 'thing')
    with op.batch_alter_table('predictions') as batch_op:
        batch_op.drop_column('thing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('thing', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
